name: Node Continuous Integration

on:
  pull_request:
    branches:
      - main


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Install dependencies
        run: npm ci

      - name: Run Unit tests
        run: npm test

      - name: Run Integration tests
        uses: matt-ball/newman-action@master
        with:
          collection: ${{ github.workspace }}/postman-colections/Integration_Tests.postman_collection.json
          environment: ${{ github.workspace }}/postman-colections/calculator.postman_environment.json
