name: Node Continuous Integration and Deployment

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Install dependencies
        run: npm ci

      - name: Run Unit tests
        run: npm test

  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-18.04
    needs: [test_pull_request]
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.2.0
        with:
          email: ${{ secrets.RENDER_EMAIL }}
          password: ${{ secrets.RENDER_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-xxxxxxxxxxxxxxxxxxxx
